version: '3.8'
services:
  mongodb:
    image: mongo:5.0.7
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  ghost:
    depends_on:
      - mongodb
    build: ../ghost
    env_file:
      - ../ghost/.env
    ports:
      - "3000:3000"
volumes:
  db:
